import turtle
import random

wn = turtle.Screen()
bob = turtle.Turtle()
turtle.speed(0)

for _ in range(10):
    x = random.randrange(30)
    
    bob.right(20 + x)
    bob.forward(20 + x)
    bob.left(25 + x)
    bob.forward(100 + x)
    bob.left(180 + x)
    bob.forward(50 + x)
    bob.right(270 + x)
    bob.forward(100 + x)
    bob.left(65 + x)
    bob.forward(55 + x)
    bob.left(40 + x)
    bob.forward(100 + x)
    bob.left(75 + x)
    bob.forward(100 + x)
    bob.left(90 + x)
    bob.forward(50 + x)
    bob.left(90 + x)
    bob.forward(120 + x)
    bob.left(90 + x)
    bob.forward(120 + x)
    bob.left(90 + x)
    bob.forward(90 + x)
    bob.left(50 + x)
    bob.forward(50 + x)
    bob.left(125 + x)
    bob.forward(125 + x)
    bob.left(180 + x)
    bob.forward(250 + x)
    bob.left(180 + x)
    bob.forward(250 + x)
    bob.left(90 + x)
    bob.forward(65 + x)
    bob.left(50 + x)
    bob.forward(120 + x)
    bob.left(180 + x)
    bob.forward(60 + x)

turtle.done()
