import turtle
import random

wn = turtle.Screen()
bob = turtle.Turtle()
turtle.speed(0)
bob.forward(90)
bob.right(90)
bob.forward(90)

for i in range(20):
    angle = 11 + i * 7
    bob.right(38 + angle)
    bob.forward(13 + angle)
    bob.left(50 + angle)
    bob.forward(15 + angle)
    bob.left(110 + angle)
    bob.forward(50 + angle)
    bob.right(148 + angle)
    bob.forward(85 + angle)
    bob.left(110 + angle)
    bob.forward(51 + angle)
    bob.left(38 + angle)
    bob.forward(110 + angle)
    bob.left(40 + angle)
    bob.forward(110 + angle)
    bob.left(51 + angle)
    bob.forward(51 + angle)
    bob.left(40 + angle)
    bob.forward(33 + angle)
    bob.left(90 + angle)
    bob.forward(110 + angle)
    bob.left(99 + angle)
    bob.forward(110 + angle) 
    bob.left(51 + angle)
    bob.forward(22 + angle)
    bob.left(148 + angle)
    bob.forward(110 + angle)
    bob.left(15 + angle)
    bob.forward(58 + angle)
    bob.left(12 + angle)
    bob.forward(13 + angle)
    bob.left(12 + angle)
    bob.forward(85 + angle)
    bob.left(10 + angle)
    bob.forward(85 + angle)
    bob.left(29 + angle)
    bob.forward(11 + angle)

turtle.done()

