import turtle

wn = turtle.Screen()
bob = turtle.Turtle()
turtle.speed(0)
bob.forward(90)
bob.right(90)
bob.forward(90)
for _ in range(20):
    import random;
    x = 11
    bob.right(38 + x )
    bob.forward(13 + x )
    bob.left(50 + x )
    bob.forward(15 + x )
    bob.left(110 + x )
    bob.forward(50 + x )
    bob.right(148 + x )
    bob.forward(85 + x )
    bob.left(110 + x )
    bob.forward(51 + x )
    bob.left(38 + x )
    bob.forward(110 + x )
    bob.left(40 + x )
    bob.forward(110 + x)
    bob.left(51 + x )
    bob.forward(51 + x )
    bob.left(40 + x )
    bob.forward(33 + x )
    bob.left(90 + x )
    bob.forward(110 + x )
    bob.left(99 + x )
    bob.forward(110 + x ) 
    bob.left(51 + x )
    bob.forward(22 + x )
    bob.left(148 + x )
    bob.forward(110 + x )
    bob.left(15 + x )
    bob.forward(58 + x )
    bob.left(12 + x )
    bob.forward(13 + x )
    bob.left(12 + x )
    bob.forward(85 + x )
    bob.left(10 + x )
    bob.forward(85 + x )
    bob.left(29 + x )
    bob.forward(11 + x )
    bob.right(12 + x )
    x = x + 7
turtle.done()