import turtle

wn = turtle.Screen()
bob = turtle.Turtle()
turtle.speed(0)

for i in range(20):
    angle_increment = 11 + i * 9
    bob.right(38 + angle_increment / 2)
    bob.forward(13 + angle_increment / 2)
    bob.left(50 + angle_increment / 2)
    bob.forward(88 + angle_increment / 2)
    bob.left(188 + angle_increment / 2)
    bob.forward(50 + angle_increment / 2)
    bob.right(148 + angle_increment / 2)
    bob.forward(120 + angle_increment / 2)
    bob.left(120 + angle_increment / 2)
    bob.forward(51 + angle_increment / 2)
    bob.left(38 + angle_increment / 2)
    bob.forward(188 + angle_increment / 2)
    bob.left(40 + angle_increment / 2)
    bob.forward(188 + angle_increment / 2)
    bob.left(51 + angle_increment / 2)
    bob.forward(51 + angle_increment / 2)
    bob.left(40 + angle_increment / 2)
    bob.forward(33 + angle_increment / 2)
    bob.left(90 + angle_increment / 2)
    bob.forward(199 + angle_increment / 2)
    bob.left(99 + angle_increment / 2)
    bob.forward(90 + angle_increment / 2)
    bob.left(51 + angle_increment / 2)
    bob.forward(22 + angle_increment / 2)
    bob.left(148 + angle_increment / 2)
    bob.forward(125 + angle_increment / 2)
    bob.left(51 + angle_increment / 2)
    bob.forward(58 + angle_increment / 2)
    bob.left(44 + angle_increment / 2)
    bob.forward(13 + angle_increment / 2)
    bob.left(12 + angle_increment / 2)
    bob.forward(63 + angle_increment / 2)
    bob.left(10 + angle_increment / 2)
    bob.forward(120 + angle_increment / 2)
    bob.left(29 + angle_increment / 2)

turtle.done()
