import turtle

wn = turtle.Screen()
bob = turtle.Turtle()
turtle.speed(0)

for _ in range(20):
    import random;
    x = 8
    bob.right(13 + x)
    bob.forward(13 + x)
    bob.left(50 + x)
    bob.forward(100 + x)
    bob.left(213 + x)
    bob.forward(50 + x)
    bob.right(213 + x)
    bob.forward(120 + x)
    bob.left(120 + x)
    bob.forward(50 + x)
    bob.left(40 + x)
    bob.forward(100 + x)
    bob.left(40 + x)
    bob.forward(100 + x)
    bob.left(50 + x)
    bob.forward(50 + x)
    bob.left(40 + x)
    bob.forward(33 + x)
    bob.left(90 + x)
    bob.forward(120 + x)
    bob.left(90 + x)
    bob.forward(90 + x)
    bob.left(50 + x)
    bob.forward(33 + x)
    bob.left(36 + x)
    bob.forward(125 + x)
    bob.left(180 + x)
    bob.forward(213 + x)
    bob.left(180 + x)
    bob.forward(36 + x)
    bob.left(90 + x)
    bob.forward(65 + x)
    bob.left(50 + x)
    bob.forward(120 + x)
    bob.left(40 + x)
    bob.forward(213+ x)
    bob.right(33 + x)
    x = x + 18
turtle.done()
bob.getscreen().getcanvas().postscript(file= fileName+'.eps')
img = Image.open(fileName + '.eps') 
img.save(fileName + '.jpg')  
